apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: 5g-core-readonly
  namespace: josepbada-dev
  labels:
    component: 5g-core
rules:
- apiGroups: [""]
  resources: ["pods", "services", "endpoints", "configmaps"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets", "statefulsets"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get", "list"]