apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: amf-subsets
  namespace: 5g-core
spec:
  host: amf-service
  subsets:
  - name: v1
    labels:
      version: v1
  - name: v2
    labels:
      version: v2