apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: smf-allow-amf-only
  namespace: 5g-core
spec:
  selector:
    matchLabels:
      app: smf
  action: ALLOW
  rules:
  - from:
    - source:
        principals:
        - "cluster.local/ns/5g-core/sa/default"
    when:
    - key: source.labels[app]
      values:
      - amf
    to:
    - operation:
        methods:
        - GET
        - POST