apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pipeline-source-pvc
  namespace: josepbada-dev
  labels:
    project: week17-5g
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi