apiVersion: v1
kind: ServiceAccount
metadata:
  name: 5g-pipeline-sa
  namespace: josepbada-dev
  labels:
    project: week17-5g
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: 5g-monitor-sa
  namespace: josepbada-dev
  labels:
    project: week17-5g
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: 5g-developer-role
  namespace: josepbada-dev
  labels:
    project: week17-5g
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log", "pods/exec"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["services", "endpoints", "configmaps"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments", "replicasets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["route.openshift.io"]
    resources: ["routes"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: 5g-pipeline-role
  namespace: josepbada-dev
  labels:
    project: week17-5g
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["configmaps", "services", "pods"]
    verbs: ["get", "list", "create", "update", "patch", "delete", "watch"]
  - apiGroups: ["route.openshift.io"]
    resources: ["routes"]
    verbs: ["get", "list", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: 5g-monitor-role
  namespace: josepbada-dev
  labels:
    project: week17-5g
rules:
  - apiGroups: [""]
    resources: ["pods", "endpoints", "services"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: 5g-developer-rb
  namespace: josepbada-dev
  labels:
    project: week17-5g
subjects:
  - kind: User
    name: josepbada
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: 5g-developer-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: 5g-pipeline-rb
  namespace: josepbada-dev
  labels:
    project: week17-5g
subjects:
  - kind: ServiceAccount
    name: 5g-pipeline-sa
    namespace: josepbada-dev
roleRef:
  kind: Role
  name: 5g-pipeline-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: 5g-monitor-rb
  namespace: josepbada-dev
  labels:
    project: week17-5g
subjects:
  - kind: ServiceAccount
    name: 5g-monitor-sa
    namespace: josepbada-dev
roleRef:
  kind: Role
  name: 5g-monitor-role
  apiGroup: rbac.authorization.k8s.io